# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug_onehot"

# disable callbacks and loggers during debugging
callbacks: null
logger: null

model:
  optimizer:
    lr: 1e-4
  net:
    token_dim: 384
    token_pair_dim: 32
    atom_dim: 128
    atom_pair_dim: 16
    N_block_atom: 3
    N_head_atom: 4
    N_block_token: 3
    N_head_token: 8
    N_query: 32
    N_key: 128
    dropout: 0.0
    token_coord_encoder: onehot
  mlp:
    input_dim: 256

extras:
  ignore_warnings: False
  enforce_tags: False

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

# uses only 1% of the training data and 5% of validation/test data

trainer:
  max_epochs: 1
  accelerator: cpu # debuggers don't like gpus
  devices: 1 # debuggers don't like multiprocessing
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor
  limit_train_batches: 0.01
  limit_val_batches: 0.05
  limit_test_batches: 0.05

data:
  num_workers: 0 # debuggers don't like multiprocessing
  pin_memory: False # disable gpu memory pin
